#!/bin/bash
cw templates soapserver.ftl dat/AdminToolAccessSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/AdminToolAccessSOWS.java
cw templates soapqualifier.ftl dat/AdminToolAccessSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/AdminToolAccessQualifier.java
cw templates soapfactory.ftl dat/AdminToolAccessSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/AdminToolAccessSOFactory.java
cw templates soapserver.ftl dat/AuctionManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/AuctionManagerSOWS.java
cw templates soapqualifier.ftl dat/AuctionManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/AuctionManagerQualifier.java
cw templates soapfactory.ftl dat/AuctionManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/AuctionManagerSOFactory.java
cw templates soapserver.ftl dat/AuthenticationServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/AuthenticationServiceWS.java
cw templates soapqualifier.ftl dat/AuthenticationServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/AuthenticationServiceQualifier.java
cw templates soapfactory.ftl dat/AuthenticationServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/AuthenticationServiceFactory.java
cw templates soapserver.ftl dat/BookingManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/BookingManagerSOWS.java
cw templates soapqualifier.ftl dat/BookingManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BookingManagerQualifier.java
cw templates soapfactory.ftl dat/BookingManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BookingManagerSOFactory.java
cw templates soapserver.ftl dat/BrowserSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/BrowserSOWS.java
cw templates soapqualifier.ftl dat/BrowserSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BrowserQualifier.java
cw templates soapfactory.ftl dat/BrowserSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BrowserSOFactory.java
cw templates soapserver.ftl dat/BuckshopCatalogueAdministratorSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/BuckshopCatalogueAdministratorSOWS.java
cw templates soapqualifier.ftl dat/BuckshopCatalogueAdministratorSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BuckshopCatalogueAdministratorQualifier.java
cw templates soapfactory.ftl dat/BuckshopCatalogueAdministratorSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BuckshopCatalogueAdministratorSOFactory.java
cw templates soapserver.ftl dat/BuckshopPartnerManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/BuckshopPartnerManagerSOWS.java
cw templates soapqualifier.ftl dat/BuckshopPartnerManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BuckshopPartnerManagerQualifier.java
cw templates soapfactory.ftl dat/BuckshopPartnerManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BuckshopPartnerManagerSOFactory.java
cw templates soapserver.ftl dat/BuckshopRedeemerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/BuckshopRedeemerSOWS.java
cw templates soapqualifier.ftl dat/BuckshopRedeemerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BuckshopRedeemerQualifier.java
cw templates soapfactory.ftl dat/BuckshopRedeemerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BuckshopRedeemerSOFactory.java
cw templates soapserver.ftl dat/BusinessManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/BusinessManagerSOWS.java
cw templates soapqualifier.ftl dat/BusinessManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BusinessManagerQualifier.java
cw templates soapfactory.ftl dat/BusinessManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/BusinessManagerSOFactory.java
cw templates soapserver.ftl dat/CAPPartnerMessengerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/CAPPartnerMessengerSOWS.java
cw templates soapqualifier.ftl dat/CAPPartnerMessengerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/CAPPartnerMessengerQualifier.java
cw templates soapfactory.ftl dat/CAPPartnerMessengerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/CAPPartnerMessengerSOFactory.java
cw templates soapserver.ftl dat/CompanySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/CompanySOWS.java
cw templates soapqualifier.ftl dat/CompanySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/CompanyQualifier.java
cw templates soapfactory.ftl dat/CompanySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/CompanySOFactory.java
cw templates soapserver.ftl dat/CreditCardServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/CreditCardServiceWS.java
cw templates soapqualifier.ftl dat/CreditCardServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/CreditCardServiceQualifier.java
cw templates soapfactory.ftl dat/CreditCardServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/CreditCardServiceFactory.java
cw templates soapserver.ftl dat/DDSAdminSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/DDSAdminSOWS.java
cw templates soapqualifier.ftl dat/DDSAdminSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/DDSAdminQualifier.java
cw templates soapfactory.ftl dat/DDSAdminSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/DDSAdminSOFactory.java
cw templates soapserver.ftl dat/FinanceManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/FinanceManagerSOWS.java
cw templates soapqualifier.ftl dat/FinanceManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/FinanceManagerQualifier.java
cw templates soapfactory.ftl dat/FinanceManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/FinanceManagerSOFactory.java
cw templates soapserver.ftl dat/FinancialContextProviderOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/FinancialContextProviderWS.java
cw templates soapqualifier.ftl dat/FinancialContextProviderOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/FinancialContextProviderQualifier.java
cw templates soapfactory.ftl dat/FinancialContextProviderOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/FinancialContextProviderFactory.java
cw templates soapserver.ftl dat/FooOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/FooWS.java
cw templates soapqualifier.ftl dat/FooOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/FooQualifier.java
cw templates soapfactory.ftl dat/FooOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/FooFactory.java
cw templates soapserver.ftl dat/GoodDayOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/GoodDayWS.java
cw templates soapqualifier.ftl dat/GoodDayOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/GoodDayQualifier.java
cw templates soapfactory.ftl dat/GoodDayOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/GoodDayFactory.java
cw templates soapserver.ftl dat/GPearnOptimizationSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/GPearnOptimizationSOWS.java
cw templates soapqualifier.ftl dat/GPearnOptimizationSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/GPearnOptimizationQualifier.java
cw templates soapfactory.ftl dat/GPearnOptimizationSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/GPearnOptimizationSOFactory.java
cw templates soapserver.ftl dat/IPHSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/IPHSOWS.java
cw templates soapqualifier.ftl dat/IPHSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/IPHQualifier.java
cw templates soapfactory.ftl dat/IPHSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/IPHSOFactory.java
cw templates soapserver.ftl dat/LottoNumberSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/LottoNumberSOWS.java
cw templates soapqualifier.ftl dat/LottoNumberSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/LottoNumberQualifier.java
cw templates soapfactory.ftl dat/LottoNumberSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/LottoNumberSOFactory.java
cw templates soapserver.ftl dat/MemberAccountManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberAccountManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberAccountManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberAccountManagerQualifier.java
cw templates soapfactory.ftl dat/MemberAccountManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberAccountManagerSOFactory.java
cw templates soapserver.ftl dat/MemberAirtimeManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberAirtimeManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberAirtimeManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberAirtimeManagerQualifier.java
cw templates soapfactory.ftl dat/MemberAirtimeManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberAirtimeManagerSOFactory.java
cw templates soapserver.ftl dat/MemberAuthenticatorSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberAuthenticatorSOWS.java
cw templates soapqualifier.ftl dat/MemberAuthenticatorSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberAuthenticatorQualifier.java
cw templates soapfactory.ftl dat/MemberAuthenticatorSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberAuthenticatorSOFactory.java
cw templates soapserver.ftl dat/MemberCreatorSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberCreatorSOWS.java
cw templates soapqualifier.ftl dat/MemberCreatorSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberCreatorQualifier.java
cw templates soapfactory.ftl dat/MemberCreatorSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberCreatorSOFactory.java
cw templates soapserver.ftl dat/MemberDetailManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberDetailManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberDetailManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberDetailManagerQualifier.java
cw templates soapfactory.ftl dat/MemberDetailManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberDetailManagerSOFactory.java
cw templates soapserver.ftl dat/MemberDiscountManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberDiscountManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberDiscountManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberDiscountManagerQualifier.java
cw templates soapfactory.ftl dat/MemberDiscountManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberDiscountManagerSOFactory.java
cw templates soapserver.ftl dat/MemberEBucksCardFactorySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberEBucksCardFactorySOWS.java
cw templates soapqualifier.ftl dat/MemberEBucksCardFactorySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberEBucksCardFactoryQualifier.java
cw templates soapfactory.ftl dat/MemberEBucksCardFactorySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberEBucksCardFactorySOFactory.java
cw templates soapserver.ftl dat/MemberEventManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberEventManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberEventManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberEventManagerQualifier.java
cw templates soapfactory.ftl dat/MemberEventManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberEventManagerSOFactory.java
cw templates soapserver.ftl dat/MemberFactorySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberFactorySOWS.java
cw templates soapqualifier.ftl dat/MemberFactorySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberFactoryQualifier.java
cw templates soapfactory.ftl dat/MemberFactorySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberFactorySOFactory.java
cw templates soapserver.ftl dat/MemberHistoryFinderSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberHistoryFinderSOWS.java
cw templates soapqualifier.ftl dat/MemberHistoryFinderSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberHistoryFinderQualifier.java
cw templates soapfactory.ftl dat/MemberHistoryFinderSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberHistoryFinderSOFactory.java
cw templates soapserver.ftl dat/MemberPaymentManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberPaymentManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberPaymentManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberPaymentManagerQualifier.java
cw templates soapfactory.ftl dat/MemberPaymentManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberPaymentManagerSOFactory.java
cw templates soapserver.ftl dat/MemberPersonalDetailsManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberPersonalDetailsManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberPersonalDetailsManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberPersonalDetailsManagerQualifier.java
cw templates soapfactory.ftl dat/MemberPersonalDetailsManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberPersonalDetailsManagerSOFactory.java
cw templates soapserver.ftl dat/MemberShoppingManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberShoppingManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberShoppingManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberShoppingManagerQualifier.java
cw templates soapfactory.ftl dat/MemberShoppingManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberShoppingManagerSOFactory.java
cw templates soapserver.ftl dat/MemberSubscriptionManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberSubscriptionManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberSubscriptionManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberSubscriptionManagerQualifier.java
cw templates soapfactory.ftl dat/MemberSubscriptionManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberSubscriptionManagerSOFactory.java
cw templates soapserver.ftl dat/MemberVoucherManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MemberVoucherManagerSOWS.java
cw templates soapqualifier.ftl dat/MemberVoucherManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberVoucherManagerQualifier.java
cw templates soapfactory.ftl dat/MemberVoucherManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MemberVoucherManagerSOFactory.java
cw templates soapserver.ftl dat/MerchantManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MerchantManagerSOWS.java
cw templates soapqualifier.ftl dat/MerchantManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantManagerQualifier.java
cw templates soapfactory.ftl dat/MerchantManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantManagerSOFactory.java
cw templates soapserver.ftl dat/MerchantPaymentSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MerchantPaymentSOWS.java
cw templates soapqualifier.ftl dat/MerchantPaymentSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantPaymentQualifier.java
cw templates soapfactory.ftl dat/MerchantPaymentSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantPaymentSOFactory.java
cw templates soapserver.ftl dat/MerchantRedeemerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MerchantRedeemerSOWS.java
cw templates soapqualifier.ftl dat/MerchantRedeemerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantRedeemerQualifier.java
cw templates soapfactory.ftl dat/MerchantRedeemerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantRedeemerSOFactory.java
cw templates soapserver.ftl dat/MerchantUserActionManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MerchantUserActionManagerSOWS.java
cw templates soapqualifier.ftl dat/MerchantUserActionManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantUserActionManagerQualifier.java
cw templates soapfactory.ftl dat/MerchantUserActionManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantUserActionManagerSOFactory.java
cw templates soapserver.ftl dat/MerchantUserAdminManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MerchantUserAdminManagerSOWS.java
cw templates soapqualifier.ftl dat/MerchantUserAdminManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantUserAdminManagerQualifier.java
cw templates soapfactory.ftl dat/MerchantUserAdminManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MerchantUserAdminManagerSOFactory.java
cw templates soapserver.ftl dat/MomentumEarnSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/MomentumEarnSOWS.java
cw templates soapqualifier.ftl dat/MomentumEarnSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MomentumEarnQualifier.java
cw templates soapfactory.ftl dat/MomentumEarnSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/MomentumEarnSOFactory.java
cw templates soapserver.ftl dat/NotifierCallbackSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/NotifierCallbackSOWS.java
cw templates soapqualifier.ftl dat/NotifierCallbackSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/NotifierCallbackQualifier.java
cw templates soapfactory.ftl dat/NotifierCallbackSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/NotifierCallbackSOFactory.java
cw templates soapserver.ftl dat/NotifierSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/NotifierSOWS.java
cw templates soapqualifier.ftl dat/NotifierSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/NotifierQualifier.java
cw templates soapfactory.ftl dat/NotifierSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/NotifierSOFactory.java
cw templates soapserver.ftl dat/PartnerFactorySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/PartnerFactorySOWS.java
cw templates soapqualifier.ftl dat/PartnerFactorySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/PartnerFactoryQualifier.java
cw templates soapfactory.ftl dat/PartnerFactorySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/PartnerFactorySOFactory.java
cw templates soapserver.ftl dat/PINMailerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/PINMailerSOWS.java
cw templates soapqualifier.ftl dat/PINMailerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/PINMailerQualifier.java
cw templates soapfactory.ftl dat/PINMailerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/PINMailerSOFactory.java
cw templates soapserver.ftl dat/PPGManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/PPGManagerSOWS.java
cw templates soapqualifier.ftl dat/PPGManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/PPGManagerQualifier.java
cw templates soapfactory.ftl dat/PPGManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/PPGManagerSOFactory.java
cw templates soapserver.ftl dat/RuleServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/RuleServiceWS.java
cw templates soapqualifier.ftl dat/RuleServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/RuleServiceQualifier.java
cw templates soapfactory.ftl dat/RuleServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/RuleServiceFactory.java
cw templates soapserver.ftl dat/SessionHandlerOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/SessionHandlerWS.java
cw templates soapqualifier.ftl dat/SessionHandlerOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/SessionHandlerQualifier.java
cw templates soapfactory.ftl dat/SessionHandlerOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/SessionHandlerFactory.java
cw templates soapserver.ftl dat/ShopCatalogueServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/ShopCatalogueServiceWS.java
cw templates soapqualifier.ftl dat/ShopCatalogueServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/ShopCatalogueServiceQualifier.java
cw templates soapfactory.ftl dat/ShopCatalogueServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/ShopCatalogueServiceFactory.java
cw templates soapserver.ftl dat/ShopOrderServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/ShopOrderServiceWS.java
cw templates soapqualifier.ftl dat/ShopOrderServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/ShopOrderServiceQualifier.java
cw templates soapfactory.ftl dat/ShopOrderServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/ShopOrderServiceFactory.java
cw templates soapserver.ftl dat/ShopPartnerServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/ShopPartnerServiceWS.java
cw templates soapqualifier.ftl dat/ShopPartnerServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/ShopPartnerServiceQualifier.java
cw templates soapfactory.ftl dat/ShopPartnerServiceOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/ShopPartnerServiceFactory.java
cw templates soapserver.ftl dat/TableEntrySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/TableEntrySOWS.java
cw templates soapqualifier.ftl dat/TableEntrySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/TableEntryQualifier.java
cw templates soapfactory.ftl dat/TableEntrySOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/TableEntrySOFactory.java
cw templates soapserver.ftl dat/TableManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/TableManagerSOWS.java
cw templates soapqualifier.ftl dat/TableManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/TableManagerQualifier.java
cw templates soapfactory.ftl dat/TableManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/TableManagerSOFactory.java
cw templates soapserver.ftl dat/TableSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/TableSOWS.java
cw templates soapqualifier.ftl dat/TableSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/TableQualifier.java
cw templates soapfactory.ftl dat/TableSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/TableSOFactory.java
cw templates soapserver.ftl dat/UserManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/UserManagerSOWS.java
cw templates soapqualifier.ftl dat/UserManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/UserManagerQualifier.java
cw templates soapfactory.ftl dat/UserManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/UserManagerSOFactory.java
cw templates soapserver.ftl dat/VirtualVoucherOrderManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/soap/VirtualVoucherOrderManagerSOWS.java
cw templates soapqualifier.ftl dat/VirtualVoucherOrderManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/VirtualVoucherOrderManagerQualifier.java
cw templates soapfactory.ftl dat/VirtualVoucherOrderManagerSOOperations.java ../eBucksServiceProxy/src/main/java/com/ebucks/corba/client/VirtualVoucherOrderManagerSOFactory.java
